apiVersion: v2
name: librechat
description: LibreChat is a chat application
type: application
version: 1.0.0
appVersion: 1.0.0
icon: https://docs.librechat.ai/assets/LibreChat.svg
dependencies:
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.5.0
    condition: meilisearch.enabled
  - name: redis
    version: 18.19.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: mongodb
    version: 15.1.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
