apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "librechat.fullname" . }}-meili
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeRef }}
  target:
    name: {{ include "librechat.fullname" . }}-meili
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: meili_master_key
