apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "librechat.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeRef }}
  target:
    name: {{ include "librechat.fullname" . }}
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: openai_api_key
    - secretKey: CREDS_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: creds_key
    - secretKey: CREDS_IV
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: creds_iv
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: jwt_secret
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: jwt_refresh_secret
    - secretKey: MONGO_URI
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: mongo_uri
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: google_client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: google_client_secret
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: google_api_key
    - secretKey: GOOGLE_CSE_ID
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: google_cse_id
    - secretKey: ASSISTANTS_API_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: assistants_api_key
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: meili_master_key
    - secretKey: FIREBASE_API_KEY
      remoteRef:
        key: {{ .Values.secrets.key }}
        property: firebase_api_key
